version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-container_name
    volumes:
      - ./nginx-ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
